CREATE TABLE IF NOT EXISTS task_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_type VARCHAR(32) NOT NULL COMMENT '任务类型: TRANSLATE/PDF_CONVERT/OCR',
    original_filename VARCHAR(255) NOT NULL COMMENT '原始文件名',
    result_filename VARCHAR(255) COMMENT '结果文件名',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING/PROCESSING/SUCCESS/FAILED',
    error_message VARCHAR(1024) COMMENT '错误信息',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finish_time TIMESTAMP
);
